# Generated by Django 4.1.4 on 2022-12-31 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('sheet_name', models.CharField(default='Supermath Correspondence Contest', max_length=50)),
                ('sheet_subname', models.CharField(default='Time Limit: 4 Minutes', max_length=50)),
                ('problem_data', models.JSONField()),
                ('sheet_type', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 12, 31, 13, 35, 10, 671608))),
                ('modified', models.DateTimeField(default=datetime.datetime(2022, 12, 31, 13, 35, 10, 671745))),
            ],
        ),
    ]
