# Generated by Django 4.1.4 on 2022-12-28 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('problem_data', models.JSONField()),
                ('sheet_type', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 7, 48, 57, 249684))),
                ('modified', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 7, 48, 57, 249692))),
            ],
        ),
    ]
