# Generated by Django 4.1.4 on 2022-12-28 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0002_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='sheet_id',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 8, 9, 56, 599872)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 8, 9, 56, 599884)),
        ),
    ]
