# Generated by Django 4.1.4 on 2022-12-31 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0003_alter_sheet_created_alter_sheet_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 13, 35, 39, 47964)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 13, 35, 39, 48103)),
        ),
    ]
