# Generated by Django 4.1.4 on 2022-12-29 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0003_remove_sheet_sheet_id_alter_sheet_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_name',
            field=models.CharField(default='Supermath Correspondence Contest', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 7, 1, 33, 401648)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 7, 1, 33, 401660)),
        ),
    ]
