# Generated by Django 4.1.4 on 2023-01-04 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0004_alter_sheet_created_alter_sheet_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 22, 53, 17, 962958)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 22, 53, 17, 963115)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_name',
            field=models.CharField(default='SuperMath Correspondence Contest', max_length=50),
        ),
    ]
