# Generated by Django 4.1.4 on 2023-01-08 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0006_sheet_sheet_answer_name_alter_sheet_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_subtype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 11, 14, 50, 231218)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 11, 14, 50, 231353)),
        ),
    ]
