# Generated by Django 4.0.5 on 2023-01-09 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmaker', '0007_sheet_sheet_subtype_alter_sheet_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 1, 24, 41, 539408)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 1, 24, 41, 539408)),
        ),
    ]
